name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up WireGuard
        uses: bengtfredh/setup-wireguard@v2
        with:
          # Endpoint in the HOST:PORT format
          endpoint: '${{ secrets.WG_ENDPOINT }}'
          # Public key of the endpoint
          endpoint_public_key: '${{ secrets.WG_PUBLICKEY }}'
          # Comma-separated list of IP addresses
          ips: '${{ secrets.WG_IPS }}'
          # Comma-separated list of netmasks
          allowed_ips: '${{ secrets.WG_ALLOWEDIPS }}'
          # Private key
          private_key: '${{ secrets.WG_PRIVATEKEY }}'
          # Preshared key
          #preshared_key: # optional
      - name: Show wg status
        run: sudo wg;sudo ip r s
      - name: Check endpoint
        run: sudo ping -W 10 -c 5 -- '${{ secrets.WG_ENDPOINT_PRIVATE_IP }}'
      - name: Add private dns
        run: sudo resolvectl dns "$ifname" '${{ secrets.DNS_SERVER }}'; sudo resolvectl dns "$ifname" '${{ secrets.DNS_DOMAIN }}'
      - name: Check endpoint dns
        run: sudo ping -W 10 -c 5 -- '${{ secrets.WG_ENDPOINT_PRIVATE_DNS }}'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
